'use client';

import useSWR from 'swr';
import { useState } from 'react';
import { api, swrFetcher } from '@/lib/api';

interface ArchiveEntry {
  id: string;
  type: string;
  title: string;
  summary: string;
  body: string;
  tags: string[];
  authorUserId?: string | null;
  authorAgentId?: string | null;
  isAutoGenerated: boolean;
  occurredAt: string;
  createdAt: string;
}

interface ArchiveStats {
  total: number;
  byType: Record<string, number>;
  recent: Array<{ id: string; type: string; title: string; occurredAt: string; isAutoGenerated: boolean }>;
}

const typeConfig: Record<string, { label: string; color: string; icon: string }> = {
  board_decision:      { label: '董事會決議', color: 'bg-purple-500/20 text-purple-400 border-purple-500/30', icon: '🗳️' },
  meeting_minutes:     { label: '會議記錄',   color: 'bg-sky-500/20 text-sky-400 border-sky-500/30', icon: '📝' },
  policy_change:       { label: '政策變更',   color: 'bg-amber-500/20 text-amber-400 border-amber-500/30', icon: '📜' },
  agent_action:        { label: 'Agent 行動', color: 'bg-slate-500/20 text-slate-400 border-slate-500/30', icon: '🤖' },
  goal_completion:     { label: '目標達成',   color: 'bg-emerald-500/20 text-emerald-400 border-emerald-500/30', icon: '✅' },
  incident:            { label: '事件記錄',   color: 'bg-red-500/20 text-red-400 border-red-500/30', icon: '⚠️' },
  financial_milestone: { label: '財務里程碑', color: 'bg-green-500/20 text-green-400 border-green-500/30', icon: '💰' },
  strategic_note:      { label: '策略備忘錄', color: 'bg-indigo-500/20 text-indigo-400 border-indigo-500/30', icon: '🧭' },
};

export default function ArchivePage() {
  const [q, setQ] = useState('');
  const [filterType, setFilterType] = useState('');
  const [selected, setSelected] = useState<ArchiveEntry | null>(null);
  const [showNew, setShowNew] = useState(false);
  const [newEntry, setNewEntry] = useState({ type: 'meeting_minutes', title: '', body: '' });
  const [submitting, setSubmitting] = useState(false);

  const queryStr = `/api/archive?${new URLSearchParams({ ...(q && { q }), ...(filterType && { type: filterType }) })}`;
  const { data: entries, mutate } = useSWR<ArchiveEntry[]>(queryStr, swrFetcher, { refreshInterval: 60000 });
  const { data: stats } = useSWR<ArchiveStats>('/api/archive/stats/summary', swrFetcher, { refreshInterval: 60000 });

  async function createEntry() {
    if (!newEntry.title || !newEntry.body) return;
    setSubmitting(true);
    try {
      await api.post('/api/archive', newEntry);
      setNewEntry({ type: 'meeting_minutes', title: '', body: '' });
      setShowNew(false);
      mutate();
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold">公司檔案庫</h2>
          <p className="text-slate-400 text-sm mt-0.5">所有決議、會議記錄與重大事件的永久記錄</p>
        </div>
        <button
          onClick={() => setShowNew(true)}
          className="bg-indigo-500 hover:bg-indigo-400 text-white text-sm font-medium px-4 py-2 rounded-lg transition-colors"
        >
          + 新增記錄
        </button>
      </div>

      {/* Stats row */}
      {stats && (
        <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
          <div className="bg-slate-800 rounded-xl p-4 border border-slate-700 col-span-2 md:col-span-1">
            <p className="text-xs text-slate-400 uppercase tracking-wider mb-1">總記錄數</p>
            <p className="text-3xl font-bold text-indigo-400">{stats.total}</p>
          </div>
          {Object.entries(typeConfig)
            .filter(([k]) => (stats.byType[k] ?? 0) > 0)
            .slice(0, 3)
            .map(([k, cfg]) => (
              <div key={k} className="bg-slate-800 rounded-xl p-4 border border-slate-700">
                <p className="text-xs text-slate-400 truncate mb-1">{cfg.icon} {cfg.label}</p>
                <p className="text-2xl font-bold">{stats.byType[k] ?? 0}</p>
              </div>
            ))}
        </div>
      )}

      {/* New entry form */}
      {showNew && (
        <div className="bg-slate-800 border border-indigo-500/30 rounded-xl p-5">
          <h3 className="text-sm font-semibold mb-3">新增記錄</h3>
          <div className="space-y-2 mb-3">
            <select
              className="w-full bg-slate-900 border border-slate-600 rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-indigo-500"
              value={newEntry.type}
              onChange={(e) => setNewEntry({ ...newEntry, type: e.target.value })}
            >
              {Object.entries(typeConfig).map(([k, v]) => (
                <option key={k} value={k}>{v.icon} {v.label}</option>
              ))}
            </select>
            <input
              className="w-full bg-slate-900 border border-slate-600 rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-indigo-500"
              placeholder="標題"
              value={newEntry.title}
              onChange={(e) => setNewEntry({ ...newEntry, title: e.target.value })}
            />
            <textarea
              className="w-full bg-slate-900 border border-slate-600 rounded-lg px-3 py-2 text-sm h-32 resize-none focus:outline-none focus:border-indigo-500"
              placeholder="內容（支援 Markdown）"
              value={newEntry.body}
              onChange={(e) => setNewEntry({ ...newEntry, body: e.target.value })}
            />
          </div>
          <div className="flex gap-2">
            <button
              onClick={createEntry}
              disabled={submitting || !newEntry.title || !newEntry.body}
              className="bg-indigo-500 hover:bg-indigo-400 disabled:opacity-50 text-white text-sm font-medium px-4 py-2 rounded-lg"
            >
              {submitting ? '儲存中...' : '儲存'}
            </button>
            <button onClick={() => setShowNew(false)} className="text-slate-400 text-sm px-4 py-2 rounded-lg">
              取消
            </button>
          </div>
        </div>
      )}

      {/* Search + filter */}
      <div className="flex gap-3">
        <input
          className="flex-1 bg-slate-800 border border-slate-700 rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-indigo-500"
          placeholder="搜尋標題、內容、標籤..."
          value={q}
          onChange={(e) => setQ(e.target.value)}
        />
        <select
          className="bg-slate-800 border border-slate-700 rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-indigo-500"
          value={filterType}
          onChange={(e) => setFilterType(e.target.value)}
        >
          <option value="">全部類型</option>
          {Object.entries(typeConfig).map(([k, v]) => (
            <option key={k} value={k}>{v.label}</option>
          ))}
        </select>
      </div>

      {/* Two-panel layout */}
      <div className="flex gap-4 min-h-[500px]">
        {/* Entry list */}
        <div className="w-80 shrink-0 space-y-2 overflow-y-auto">
          {entries?.map((entry) => {
            const cfg = typeConfig[entry.type] ?? { label: entry.type, color: 'bg-slate-600 text-slate-300 border-slate-600', icon: '📄' };
            const isSelected = selected?.id === entry.id;
            return (
              <button
                key={entry.id}
                onClick={() => setSelected(entry)}
                className={`w-full text-left p-4 rounded-xl border transition-colors ${
                  isSelected
                    ? 'bg-slate-700 border-indigo-500/50'
                    : 'bg-slate-800 border-slate-700 hover:border-slate-500'
                }`}
              >
                <div className="flex items-center gap-2 mb-1.5">
                  <span className={`text-xs px-2 py-0.5 rounded-full border ${cfg.color}`}>
                    {cfg.icon} {cfg.label}
                  </span>
                  {!entry.isAutoGenerated && (
                    <span className="text-xs text-slate-500">手動</span>
                  )}
                </div>
                <p className="text-sm font-medium leading-snug line-clamp-2">{entry.title}</p>
                <p className="text-xs text-slate-500 mt-1">
                  {new Date(entry.occurredAt).toLocaleDateString('zh-TW', {
                    year: 'numeric', month: 'short', day: 'numeric',
                  })}
                </p>
              </button>
            );
          })}
          {entries?.length === 0 && (
            <div className="text-center py-12 text-slate-500">
              <p className="text-3xl mb-2">📁</p>
              <p className="text-sm">尚無記錄</p>
            </div>
          )}
        </div>

        {/* Entry detail */}
        <div className="flex-1 bg-slate-800 border border-slate-700 rounded-xl overflow-hidden">
          {selected ? (
            <div className="h-full overflow-y-auto">
              <div className="p-6 border-b border-slate-700">
                <div className="flex items-start justify-between gap-3 mb-3">
                  <div>
                    {(() => {
                      const cfg = typeConfig[selected.type] ?? { label: selected.type, color: 'bg-slate-600 text-slate-300 border-slate-600', icon: '📄' };
                      return (
                        <span className={`text-xs px-2 py-0.5 rounded-full border ${cfg.color} mb-2 inline-block`}>
                          {cfg.icon} {cfg.label}
                        </span>
                      );
                    })()}
                    <h3 className="text-lg font-semibold mt-1">{selected.title}</h3>
                  </div>
                  <div className="text-right shrink-0">
                    <p className="text-xs text-slate-400">
                      {new Date(selected.occurredAt).toLocaleDateString('zh-TW', {
                        year: 'numeric', month: 'long', day: 'numeric',
                      })}
                    </p>
                    <p className="text-xs text-slate-500 mt-0.5">
                      {selected.isAutoGenerated ? '⚙️ 系統自動生成' : '✍️ 人工記錄'}
                    </p>
                  </div>
                </div>
                {selected.tags.length > 0 && (
                  <div className="flex flex-wrap gap-1">
                    {selected.tags.map((t) => (
                      <span key={t} className="text-xs bg-slate-700 text-slate-400 rounded px-2 py-0.5">{t}</span>
                    ))}
                  </div>
                )}
              </div>
              <div className="p-6">
                <div className="prose prose-invert prose-sm max-w-none">
                  <pre className="whitespace-pre-wrap text-sm text-slate-300 font-sans leading-relaxed">{selected.body}</pre>
                </div>
              </div>
            </div>
          ) : (
            <div className="h-full flex items-center justify-center text-slate-500">
              <div className="text-center">
                <p className="text-4xl mb-3">📋</p>
                <p>選擇一筆記錄查看詳情</p>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
