import Anthropic from '@anthropic-ai/sdk';
import { config } from '../config';
import { prisma } from '../lib/prisma';

/**
 * ArchiveService — the company's institutional memory.
 *
 * Automatically records every significant company event as an archive entry:
 * - Board decisions (passed/rejected proposals)
 * - Meeting minutes (aggregated from proposal discussions)
 * - Goal completions (with AI-generated summary of what was achieved)
 * - Agent actions (major autonomous decisions by the CEO/CFO)
 * - Financial milestones (first income, runway changes)
 * - Policy changes (constitution amendments)
 * - Incidents (stuck tasks, self-healing events)
 *
 * The archive is append-only and searchable.
 * Humans can also add manual entries (strategic notes, meeting minutes).
 */
export class ArchiveService {
  private ai: Anthropic;

  constructor() {
    this.ai = new Anthropic({
      apiKey: config.ai.apiKey,
      baseURL: config.ai.baseUrl,
    });
  }

  /**
   * Record a board decision after a proposal resolves.
   */
  async recordBoardDecision(proposalId: string): Promise<void> {
    const proposal = await prisma.proposal.findUnique({
      where: { id: proposalId },
      include: { votes: true },
    });

    if (!proposal) return;

    const yesVotes = proposal.votes.filter((v) => v.choice === 'yes').length;
    const noVotes = proposal.votes.filter((v) => v.choice === 'no').length;
    const abstainVotes = proposal.votes.filter((v) => v.choice === 'abstain').length;
    const totalVotes = proposal.votes.length;

    const outcome =
      proposal.status === 'passed' ? '✅ 通過'
      : proposal.status === 'rejected' ? '❌ 否決'
      : proposal.status === 'expired' ? '⏰ 過期'
      : proposal.status;

    const typeLabel: Record<string, string> = {
      constitution_amendment: '修憲',
      profit_distribution: '利潤分配調整',
      agent_hire: '雇用 Agent',
      agent_fire: '解除 Agent',
      budget_allocation: '預算分配',
      strategic_pivot: '策略轉向',
      custom: '其他決議',
    };

    const body = `## 決議摘要

**提案類型：** ${typeLabel[proposal.type] ?? proposal.type}
**提案標題：** ${proposal.title}
**最終結果：** ${outcome}

### 說明
${proposal.description}

### 投票結果
| 選項 | 票數 |
|---|---|
| 贊成 | ${yesVotes} 票 |
| 反對 | ${noVotes} 票 |
| 棄權 | ${abstainVotes} 票 |
| **合計** | **${totalVotes} 票** |

### 執行狀況
${proposal.executionNote ?? '（尚未執行）'}

### 投票截止
${new Date(proposal.votingDeadline).toLocaleDateString('zh-TW', { year: 'numeric', month: 'long', day: 'numeric' })}`;

    const summary = `董事會就「${proposal.title}」進行投票。結果：${outcome}（${yesVotes}/${totalVotes}票贊成）。`;

    await prisma.archiveEntry.create({
      data: {
        type: 'board_decision',
        title: `董事會決議：${proposal.title}`,
        summary,
        body,
        proposalId: proposal.id,
        tags: [proposal.type, proposal.status, '董事會'],
        isAutoGenerated: true,
        occurredAt: new Date(),
      },
    });
  }

  /**
   * Record a goal completion with AI-generated achievement summary.
   */
  async recordGoalCompletion(goalId: string): Promise<void> {
    const goal = await prisma.goal.findUnique({
      where: { id: goalId },
      include: {
        tasks: {
          select: { title: true, status: true, completedAt: true },
          orderBy: { completedAt: 'asc' },
        },
      },
    });

    if (!goal) return;

    const doneTasks = goal.tasks.filter((t) => t.status === 'done');
    const taskList = doneTasks.map((t) => `- ${t.title}`).join('\n');

    const aiSummary = await this.generateGoalSummary(goal.title, goal.description, taskList);

    const body = `## 目標達成報告

**目標：** ${goal.title}
${goal.description ? `**說明：** ${goal.description}\n` : ''}
**完成日期：** ${new Date().toLocaleDateString('zh-TW', { year: 'numeric', month: 'long', day: 'numeric' })}
**完成任務數：** ${doneTasks.length}/${goal.tasks.length}
**自愈次數：** ${goal.selfHealCount}（系統自動換策略次數）

### 完成的任務
${taskList || '（無任務記錄）'}

### AI 成就摘要
${aiSummary}`;

    await prisma.archiveEntry.create({
      data: {
        type: 'goal_completion',
        title: `目標達成：${goal.title}`,
        summary: aiSummary.slice(0, 200),
        body,
        goalId: goal.id,
        tags: ['目標完成', '里程碑'],
        isAutoGenerated: true,
        occurredAt: new Date(),
      },
    });
  }

  /**
   * Record a policy/constitution change.
   */
  async recordPolicyChange(opts: {
    changeTitle: string;
    description: string;
    previousValue?: string;
    newValue?: string;
    proposalId?: string;
  }): Promise<void> {
    const body = `## 政策變更記錄

**變更項目：** ${opts.changeTitle}
**說明：** ${opts.description}

${opts.previousValue ? `**變更前：**\n${opts.previousValue}\n` : ''}
${opts.newValue ? `**變更後：**\n${opts.newValue}\n` : ''}
${opts.proposalId ? `**相關提案：** ${opts.proposalId}` : ''}

**生效日期：** ${new Date().toLocaleDateString('zh-TW', { year: 'numeric', month: 'long', day: 'numeric' })}`;

    await prisma.archiveEntry.create({
      data: {
        type: 'policy_change',
        title: `政策變更：${opts.changeTitle}`,
        summary: opts.description.slice(0, 200),
        body,
        proposalId: opts.proposalId,
        tags: ['政策', '法規', '變更'],
        isAutoGenerated: true,
        occurredAt: new Date(),
      },
    });
  }

  /**
   * Record an incident (stuck tasks, self-healing, system events).
   */
  async recordIncident(opts: {
    title: string;
    description: string;
    severity: 'low' | 'medium' | 'high';
    resolution?: string;
  }): Promise<void> {
    const severityLabel = { low: '低', medium: '中', high: '高' }[opts.severity];

    const body = `## 事件記錄

**事件：** ${opts.title}
**嚴重程度：** ${severityLabel}
**發生時間：** ${new Date().toLocaleString('zh-TW')}

### 事件說明
${opts.description}

${opts.resolution ? `### 處理方式\n${opts.resolution}` : '### 處理方式\n（尚未解決）'}`;

    await prisma.archiveEntry.create({
      data: {
        type: 'incident',
        title: `事件：${opts.title}`,
        summary: opts.description.slice(0, 200),
        body,
        tags: ['事件', opts.severity, '系統'],
        isAutoGenerated: true,
        occurredAt: new Date(),
      },
    });
  }

  /**
   * Create a manual archive entry (for human board members or CEO agent).
   */
  async createManual(opts: {
    type: string;
    title: string;
    summary: string;
    body: string;
    tags?: string[];
    authorUserId?: string;
    authorAgentId?: string;
    occurredAt?: Date;
  }): Promise<typeof prisma.archiveEntry extends { create: (args: { data: infer T }) => unknown } ? T : never> {
    return prisma.archiveEntry.create({
      data: {
        type: opts.type as 'board_decision' | 'meeting_minutes' | 'policy_change' | 'agent_action' | 'goal_completion' | 'incident' | 'financial_milestone' | 'strategic_note',
        title: opts.title,
        summary: opts.summary,
        body: opts.body,
        tags: opts.tags ?? [],
        authorUserId: opts.authorUserId,
        authorAgentId: opts.authorAgentId,
        isAutoGenerated: false,
        occurredAt: opts.occurredAt ?? new Date(),
      },
    }) as never;
  }

  /**
   * Search archive entries.
   */
  async search(opts: {
    q?: string;
    type?: string;
    startDate?: Date;
    endDate?: Date;
    limit?: number;
  }) {
    return prisma.archiveEntry.findMany({
      where: {
        ...(opts.type && { type: opts.type as 'board_decision' | 'meeting_minutes' | 'policy_change' | 'agent_action' | 'goal_completion' | 'incident' | 'financial_milestone' | 'strategic_note' }),
        ...(opts.startDate || opts.endDate
          ? {
              occurredAt: {
                ...(opts.startDate && { gte: opts.startDate }),
                ...(opts.endDate && { lte: opts.endDate }),
              },
            }
          : {}),
        ...(opts.q
          ? {
              OR: [
                { title: { contains: opts.q, mode: 'insensitive' as const } },
                { summary: { contains: opts.q, mode: 'insensitive' as const } },
                { body: { contains: opts.q, mode: 'insensitive' as const } },
                { tags: { has: opts.q } },
              ],
            }
          : {}),
      },
      orderBy: { occurredAt: 'desc' },
      take: opts.limit ?? 50,
    });
  }

  private async generateGoalSummary(
    title: string,
    description: string | null,
    taskList: string,
  ): Promise<string> {
    try {
      const response = await this.ai.messages.create({
        model: config.ai.model,
        max_tokens: 300,
        system: '你是公司的秘書 AI。用繁體中文撰寫一段簡潔的目標達成摘要（100字以內），重點放在商業價值和成果。',
        messages: [
          {
            role: 'user',
            content: `目標：${title}\n${description ? `說明：${description}\n` : ''}完成的任務：\n${taskList}\n\n請撰寫達成摘要：`,
          },
        ],
      });

      return response.content
        .filter((b) => b.type === 'text')
        .map((b) => (b as { type: 'text'; text: string }).text)
        .join('');
    } catch {
      return `目標「${title}」已成功完成，共完成 ${taskList.split('\n').length} 個任務。`;
    }
  }
}
