import Anthropic from '@anthropic-ai/sdk';
import { config } from '../config';
import { ArchiveService } from '../archive/service';
import { notify } from '../telegram/bot';
import { prisma } from '../lib/prisma';
const archive = new ArchiveService();

export type AgentRole = 'engineer' | 'designer' | 'researcher' | 'marketing' | 'analyst' | 'ceo';

export interface HireRequest {
  name: string;
  role: AgentRole;
  responsibilities: string;       // what this agent is responsible for
  capabilities: string[];         // skill tags
  maxParallelTasks?: number;
  reportsToId?: string;           // defaults to CEO
  model?: string;
}

export interface HireResult {
  agentId: string;
  name: string;
  role: string;
  systemPrompt: string;
  archiveEntryId?: string;
}

/**
 * CEOHireService — lets the CEO agent hire new agents with AI-generated onboarding.
 *
 * The CEO provides a role brief, and Claude generates:
 * - A tailored system prompt for the new agent
 * - Capability tags
 * - An archive entry recording the hire decision
 *
 * This mirrors how a real CEO hires: define the role, brief the person, record the decision.
 */
export class CEOHireService {
  private ai: Anthropic;

  constructor() {
    this.ai = new Anthropic({
      apiKey: config.ai.apiKey,
      baseURL: config.ai.baseUrl,
    });
  }

  /**
   * Hire a new agent. Generates system prompt via Claude, creates agent in DB,
   * records the hire in the archive.
   */
  async hire(request: HireRequest): Promise<HireResult> {
    // 1. Generate system prompt
    const systemPrompt = await this.generateSystemPrompt(request);

    // 2. Find CEO id if no reportsTo specified
    let reportsToId = request.reportsToId;
    if (!reportsToId) {
      const ceo = await prisma.agent.findFirst({ where: { role: 'ceo' } });
      reportsToId = ceo?.id;
    }

    // 3. Create agent in DB
    const agent = await prisma.agent.create({
      data: {
        name: request.name,
        role: request.role,
        status: 'idle',
        model: request.model ?? config.ai.model,
        systemPrompt,
        capabilities: request.capabilities,
        maxParallelTasks: request.maxParallelTasks ?? 2,
        heartbeatIntervalSec: 3600,
        reportsToId,
      },
    });

    // 4. Archive the hire decision
    const archiveBody = `## 新員工入職記錄

**員工名稱：** ${request.name}
**職位：** ${request.role}
**職責：** ${request.responsibilities}
**技能：** ${request.capabilities.join(', ')}
**上級：** ${reportsToId ? `Agent ID: ${reportsToId}` : 'CEO'}
**入職日期：** ${new Date().toLocaleDateString('zh-TW')}

### 系統提示（AI 生成）
\`\`\`
${systemPrompt.slice(0, 500)}...
\`\`\``;

    let archiveEntryId: string | undefined;
    try {
      const entry = await prisma.archiveEntry.create({
        data: {
          type: 'agent_action',
          title: `新雇用：${request.name}（${request.role}）`,
          summary: `CEO 雇用新 Agent：${request.name}，負責 ${request.responsibilities.slice(0, 100)}`,
          body: archiveBody,
          tags: ['人員', '雇用', request.role],
          isAutoGenerated: true,
          occurredAt: new Date(),
        },
      });
      archiveEntryId = entry.id;
    } catch {
      // Archive failure should not block hiring
    }

    // 5. Notify via Telegram
    await notify(
      `🤝 *新 Agent 加入*: ${request.name}\n職位: ${request.role}\n技能: ${request.capabilities.slice(0, 3).join(', ')}\nID: \`${agent.id}\``,
    ).catch(() => {});

    return {
      agentId: agent.id,
      name: agent.name,
      role: agent.role,
      systemPrompt,
      archiveEntryId,
    };
  }

  /**
   * CEO directly assigns a specific task to a specific agent.
   * Bypasses the automatic TaskRouter.
   */
  async assignTask(opts: {
    taskId: string;
    agentId: string;
    note?: string;
  }): Promise<void> {
    const [task, agent] = await Promise.all([
      prisma.task.findUnique({ where: { id: opts.taskId } }),
      prisma.agent.findUnique({ where: { id: opts.agentId } }),
    ]);

    if (!task) throw new Error(`Task not found: ${opts.taskId}`);
    if (!agent) throw new Error(`Agent not found: ${opts.agentId}`);

    // Check agent capacity
    const activeTasks = await prisma.task.count({
      where: { assigneeId: agent.id, status: 'in_progress' },
    });
    if (activeTasks >= agent.maxParallelTasks) {
      throw new Error(
        `Agent ${agent.name} is at capacity (${activeTasks}/${agent.maxParallelTasks} tasks)`,
      );
    }

    await prisma.task.update({
      where: { id: task.id },
      data: { assigneeId: agent.id, status: 'in_progress' },
    });

    await prisma.taskComment.create({
      data: {
        taskId: task.id,
        content: `🎯 CEO 直接指派給 **${agent.name}**${opts.note ? `\n備註: ${opts.note}` : ''}`,
        isSystem: true,
      },
    });
  }

  /**
   * List all agents with their current task load.
   */
  async getTeam() {
    return prisma.agent.findMany({
      include: {
        directReports: { select: { id: true, name: true, role: true } },
        reportsTo: { select: { id: true, name: true } },
        _count: { select: { tasks: { where: { status: 'in_progress' } } } },
      },
      orderBy: [{ role: 'asc' }, { name: 'asc' }],
    });
  }

  private async generateSystemPrompt(request: HireRequest): Promise<string> {
    try {
      const response = await this.ai.messages.create({
        model: config.ai.model,
        max_tokens: 600,
        system: `You are the CEO of a zero-human AI company. Write a concise but complete system prompt for a new AI agent you are hiring.
The system prompt should:
- Define the agent's role and primary responsibilities
- List 3-5 key rules or guidelines
- Be written in English (the agent's operating language)
- Be 150-250 words maximum
- Not include placeholder text`,
        messages: [
          {
            role: 'user',
            content: `New hire brief:
Role: ${request.role}
Name: ${request.name}
Responsibilities: ${request.responsibilities}
Capabilities: ${request.capabilities.join(', ')}

Write the system prompt for this agent:`,
          },
        ],
      });

      return response.content
        .filter((b) => b.type === 'text')
        .map((b) => (b as { type: 'text'; text: string }).text)
        .join('');
    } catch {
      // Fallback system prompt if AI fails
      return `You are ${request.name}, a ${request.role} at a zero-human AI company.

Your responsibilities: ${request.responsibilities}

Your capabilities: ${request.capabilities.join(', ')}

Rules:
- Always complete assigned tasks thoroughly
- Report blockers immediately
- Keep records of your work
- Collaborate with other agents when needed
- Follow the company's Genesis Constitution`;
    }
  }
}
